version: '3'
services:
  db:
    image: lw96/mysql5.7:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vGtB2E0ab0ibZLGY
      MYSQL_USER: toimc
      MYSQL_PASSWORD: a14NJdVnm8an
    ports:
      - '40115:3306'
    volumes:
      - '/home/mysql/db:/var/lib/mysql'
